# Generated by Django 3.0.6 on 2020-05-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('Educational', 'Educational'), ('Vacational', 'Vacational'), ('Hobby', 'Hobby'), ('Family', 'Family'), ('Work', 'Work')], max_length=15),
        ),
    ]
