# Generated by Django 3.0.6 on 2020-05-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gala', '0002_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Educational', 'Educational'), ('Vacational', 'Vacational'), ('Hobby', 'Hobby'), ('Family', 'Family'), ('Work', 'Work')], max_length=15),
        ),
    ]
