# Generated by Django 3.0.6 on 2020-05-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gala', '0003_auto_20200522_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
